#!/bin/bash

# 📋 COMMANDES UTILES AKIG v3.0

echo "🚀 AKIG v3.0 - COMMANDES UTILES"
echo "================================"
echo ""

# ============= DÉMARRAGE =============
echo "🟢 DÉMARRAGE"
echo "docker-compose up -d                    # Démarrer tout"
echo "docker-compose ps                       # Vérifier services"
echo "docker-compose logs -f akig-backend     # Logs backend"
echo ""

# ============= VÉRIFICATIONS =============
echo "✅ VÉRIFICATIONS"
echo "curl http://localhost:4000/api/health   # Health check backend"
echo "curl http://localhost:3000              # Health check frontend"
echo "docker ps | grep akig                   # Services AKIG"
echo ""

# ============= BASE DE DONNÉES =============
echo "📊 BASE DE DONNÉES"
echo "# Accéder à PostgreSQL"
echo "docker exec -it akig-db psql -U akig_user -d akig"
echo ""
echo "# Commandes SQL utiles (une fois connecté):"
echo "\\dt                                    # Lister les tables"
echo "SELECT COUNT(*) FROM impayes;           # Compter impayés"
echo "SELECT COUNT(*) FROM locataires;       # Compter locataires"
echo "SELECT * FROM missions LIMIT 5;        # Voir missions"
echo "\\q                                     # Quitter"
echo ""

# ============= REDIS =============
echo "💾 REDIS CACHE"
echo "# Accéder à Redis"
echo "docker exec -it akig-cache redis-cli"
echo ""
echo "# Commandes Redis (une fois connecté):"
echo "PING                                    # Test connection"
echo "KEYS '*'                                # Voir toutes les clés"
echo "GET perms:user-id-123                  # Voir une clé"
echo "FLUSHDB                                 # Vider le cache"
echo "INFO memory                             # Stats mémoire"
echo "QUIT                                    # Quitter"
echo ""

# ============= LOGS =============
echo "📝 LOGS"
echo "docker logs -f akig-backend             # Backend temps réel"
echo "docker logs -f akig-frontend            # Frontend temps réel"
echo "docker logs -f akig-db                  # Database temps réel"
echo "docker logs -f akig-cache               # Redis temps réel"
echo "docker logs akig-backend | grep ERROR   # Erreurs backend"
echo ""

# ============= MONITORING =============
echo "📈 MONITORING"
echo "curl http://localhost:9090              # Prometheus (UI)"
echo "curl http://localhost:3001              # Grafana"
echo ""
echo "# Queries Prometheus utiles:"
echo "up                                      # Up status tous services"
echo "rate(http_requests_total[5m])           # Taux requêtes/sec"
echo "histogram_quantile(0.95, http_request_duration_seconds_bucket[5m])"
echo "                                        # Response time p95"
echo ""

# ============= PERFORMANCE =============
echo "⚡ PERFORMANCE"
echo "# Tester un endpoint"
echo "curl -w '%{time_total}s\\n' http://localhost:4000/api/agents/classement/jour"
echo ""
echo "# Bench avec ab"
echo "ab -n 1000 -c 100 http://localhost:4000/api/dashboard/resume"
echo ""
echo "# Bench avec hey"
echo "hey -n 1000 -c 100 http://localhost:4000/api/dashboard/resume"
echo ""

# ============= DÉVELOPPEMENT =============
echo "👨‍💻 DÉVELOPPEMENT"
echo "# Linter + formater code"
echo "npm run lint --workspace=backend        # ESLint"
echo "npm run format --workspace=backend      # Prettier"
echo ""
echo "# Tests"
echo "npm test --workspace=backend            # Unit tests"
echo "npm run test:watch --workspace=backend  # Watch mode"
echo ""
echo "# Build Docker"
echo "docker build -f backend/Dockerfile -t akig:latest ./backend"
echo "docker build -f frontend/Dockerfile -t akig-frontend:latest ./frontend"
echo ""

# ============= NETTOYAGE =============
echo "🧹 NETTOYAGE"
echo "docker-compose down                     # Arrêter tout"
echo "docker-compose down -v                  # Arrêter + supprimer volumes"
echo "docker-compose restart                  # Redémarrer"
echo "docker ps -a                            # Voir tous containers"
echo "docker images | grep akig               # Voir images"
echo ""

# ============= UTILITIES =============
echo "🔧 UTILITIES"
echo "# Vérifier les dépendances"
echo "npm ls --workspace=backend | head -50   # Backend deps"
echo "npm ls --workspace=frontend | head -50  # Frontend deps"
echo ""
echo "# Maj dépendances"
echo "npm update --workspace=backend"
echo "npm audit --workspace=backend           # Security audit"
echo ""

# ============= API TESTING =============
echo "🧪 API TESTING"
echo "# GET "
echo "curl http://localhost:4000/api/agents/classement/jour"
echo ""
echo "# POST avec données"
echo "curl -X POST http://localhost:4000/api/recouvrement/appel \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"locataire_id\": \"123\", \"agent_id\": \"456\"}'"
echo ""

# ============= DEBUGGING =============
echo "🐛 DEBUGGING"
echo "# Vérifier réseau"
echo "docker network ls                       # Réseaux"
echo "docker network inspect akig-network     # Détails réseau"
echo ""
echo "# Health check complet"
echo "echo '=== Backend ===' && curl http://localhost:4000/api/health"
echo "echo '=== Frontend ===' && curl -I http://localhost:3000"
echo "echo '=== Prometheus ===' && curl -I http://localhost:9090"
echo "echo '=== Grafana ===' && curl -I http://localhost:3001"
echo ""

# ============= PRODUCTION =============
echo "🚀 PRODUCTION"
echo "# Blue-green deploy"
echo "docker tag akig:latest akig:v3.0"
echo "docker push akig:v3.0"
echo ""
echo "# Kubernetes (si ready)"
echo "kubectl apply -f ops/k8s/deployment.yaml"
echo "kubectl apply -f ops/k8s/service.yaml"
echo "kubectl apply -f ops/k8s/ingress.yaml"
echo ""

# ============= TROUBLESHOOTING =============
echo "🆘 TROUBLESHOOTING"
echo ""
echo "❌ Backend ne démarre pas?"
echo "   → docker logs akig-backend | tail -50"
echo "   → Vérifier DATABASE_URL dans .env"
echo ""
echo "❌ BD indisponible?"
echo "   → docker restart akig-db"
echo "   → Voir runbook: /ops/runbooks/INCIDENTS.md"
echo ""
echo "❌ Cache slow?"
echo "   → docker exec akig-cache redis-cli INFO memory"
echo "   → Si >90% utilisé: redis-cli FLUSHDB"
echo ""
echo "❌ Requête lente?"
echo "   → Vérifier: curl -w '%{time_total}s' ..."
echo "   → Voir dashboard: http://localhost:3001"
echo ""

# ============= RESSOURCES =============
echo "📚 RESSOURCES"
echo "Documentation:    /docs"
echo "Runbooks:         /ops/runbooks/INCIDENTS.md"
echo "Dev Setup:        /docs/onboarding/DEVELOPER_SETUP.md"
echo "ADRs:             /docs/adr/README.md"
echo ""

# ============= RACCOURCIS =============
echo "⌨️  RACCOURCIS (À ajouter dans ~/.bashrc)"
echo ""
echo "# Ajouter ces lignes dans ~/.bashrc ou ~/.zshrc:"
echo ""
echo "# AKIG shortcuts"
echo "alias akig-start='cd ~/akig && docker-compose up -d'"
echo "alias akig-stop='cd ~/akig && docker-compose down'"
echo "alias akig-logs='cd ~/akig && docker-compose logs -f akig-backend'"
echo "alias akig-db='docker exec -it akig-db psql -U akig_user -d akig'"
echo "alias akig-redis='docker exec -it akig-cache redis-cli'"
echo "alias akig-health='curl http://localhost:4000/api/health | jq'"
echo ""

echo ""
echo "✅ Besoin d'aide? Slack #dev-akig ou check /docs/"
