/**
 * AKIG SDK Usage Examples
 * TypeScript examples showing how to use the generated SDK client
 * 
 * Generated by: openapi-typescript-codegen
 * Generated from: backend/openapi-spec.js
 */

// @ts-ignore - Client will be generated by SDK codegen
import { Client } from './client';

// Initialize client with environment variables
// @ts-ignore
const client = new Client({
  BASE: process.env.AKIG_API_URL || 'http://localhost:4002/api',
  TOKEN: process.env.AKIG_TOKEN
});

/**
 * Example 1: Get current authenticated user
 */
async function getCurrentUser() {
  try {
    const me = await client.developerPortal.getDevMe();
    console.log('Current User:', me);
    return me;
  } catch (error) {
    console.error('Failed to get current user:', error);
  }
}

/**
 * Example 2: Authentication - Login
 */
async function loginUser(email: string, password: string) {
  try {
    const result = await client.authentication.loginUser({
      email,
      password
    });
    console.log('Login successful:', result);
    // Store token for future requests
    client.setConfig({ TOKEN: result.token });
    return result;
  } catch (error) {
    console.error('Login failed:', error);
  }
}

/**
 * Example 3: User Registration
 */
async function registerUser(email: string, password: string, name: string) {
  try {
    const user = await client.authentication.registerUser({
      email,
      password,
      name
    });
    console.log('User registered:', user);
    return user;
  } catch (error) {
    console.error('Registration failed:', error);
  }
}

/**
 * Example 4: List all contracts
 */
async function listContracts() {
  try {
    const result = await client.contracts.listContracts({
      skip: 0,
      limit: 20,
      status: 'active'
    });
    console.log('Contracts:', result.contracts);
    console.log('Total:', result.total);
    return result;
  } catch (error) {
    console.error('Failed to list contracts:', error);
  }
}

/**
 * Example 5: Create a new contract
 */
async function createContract(title: string, amount: number) {
  try {
    const contract = await client.contracts.createContract({
      title,
      description: 'Contract description',
      amount,
      startDate: new Date().toISOString().split('T')[0],
      endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
        .toISOString()
        .split('T')[0]
    });
    console.log('Contract created:', contract);
    return contract;
  } catch (error) {
    console.error('Failed to create contract:', error);
  }
}

/**
 * Example 6: Get specific contract
 */
async function getContract(contractId: number) {
  try {
    const contract = await client.contracts.getContract({
      contractId
    });
    console.log('Contract details:', contract);
    return contract;
  } catch (error) {
    console.error('Failed to get contract:', error);
  }
}

/**
 * Example 7: Update contract
 */
async function updateContract(
  contractId: number,
  updates: { title?: string; amount?: number }
) {
  try {
    const contract = await client.contracts.updateContract(
      { contractId },
      updates
    );
    console.log('Contract updated:', contract);
    return contract;
  } catch (error) {
    console.error('Failed to update contract:', error);
  }
}

/**
 * Example 8: Delete contract
 */
async function deleteContract(contractId: number) {
  try {
    await client.contracts.deleteContract({ contractId });
    console.log('Contract deleted successfully');
  } catch (error) {
    console.error('Failed to delete contract:', error);
  }
}

/**
 * Example 9: Process payment
 */
async function createPayment(
  contractId: number,
  amount: number,
  method: 'card' | 'bank' | 'paypal'
) {
  try {
    const payment = await client.payments.createPayment({
      contractId,
      amount,
      method
    });
    console.log('Payment created:', payment);
    return payment;
  } catch (error) {
    console.error('Failed to create payment:', error);
  }
}

/**
 * Example 10: List payments
 */
async function listPayments() {
  try {
    const result = await client.payments.listPayments({
      skip: 0,
      limit: 20
    });
    console.log('Payments:', result.payments);
    console.log('Total:', result.total);
    return result;
  } catch (error) {
    console.error('Failed to list payments:', error);
  }
}

/**
 * Example 11: Export data
 */
async function exportData(
  format: 'csv' | 'json' | 'xlsx',
  type: 'contracts' | 'payments' | 'users'
) {
  try {
    const blob = await client.exports.exportData({
      format,
      type,
      filters: {}
    });
    console.log('Export data:', blob);
    // Save to file in Node.js or download in browser
    return blob;
  } catch (error) {
    console.error('Failed to export data:', error);
  }
}

/**
 * Example 12: Create API token for programmatic access
 */
async function createApiToken(name: string, scopes: string[], expiresIn?: string) {
  try {
    const result = await client.developerPortal.createToken({
      name,
      scopes,
      expiresIn
    });
    console.log('API Token created:', result.token);
    console.log('Token value (save this securely):', result.value);
    return result;
  } catch (error) {
    console.error('Failed to create API token:', error);
  }
}

/**
 * Example 13: List all API tokens
 */
async function listApiTokens() {
  try {
    const result = await client.developerPortal.listTokens();
    console.log('Your API Tokens:', result.tokens);
    return result;
  } catch (error) {
    console.error('Failed to list API tokens:', error);
  }
}

/**
 * Example 14: Get token audit log
 */
async function getTokenAuditLog(tokenId: number) {
  try {
    const result = await client.developerPortal.getToken({ tokenId });
    console.log('Token details:', result);
    return result;
  } catch (error) {
    console.error('Failed to get token audit log:', error);
  }
}

/**
 * Example 15: Revoke API token
 */
async function revokeApiToken(tokenId: number) {
  try {
    await client.developerPortal.revokeToken({ tokenId });
    console.log('API token revoked successfully');
  } catch (error) {
    console.error('Failed to revoke API token:', error);
  }
}

/**
 * Example 16: Health check
 */
async function healthCheck() {
  try {
    const health = await client.health.getHealth();
    console.log('System health:', health);
    return health;
  } catch (error) {
    console.error('Health check failed:', error);
  }
}

/**
 * Complex Example: Full workflow
 * 1. Register user
 * 2. Login
 * 3. Create contract
 * 4. Process payment
 * 5. Export data
 */
async function fullWorkflow() {
  console.log('\n=== AKIG SDK Full Workflow Example ===\n');

  try {
    // 1. Register
    console.log('1. Registering user...');
    const user = await registerUser(
      'user@example.com',
      'SecurePassword123!',
      'John Doe'
    );

    // 2. Login
    console.log('\n2. Logging in...');
    const loginResult = await loginUser('user@example.com', 'SecurePassword123!');

    // 3. Create contract
    console.log('\n3. Creating contract...');
    const contract = await createContract('Service Agreement', 5000);

    // 4. Process payment
    console.log('\n4. Processing payment...');
    if (contract?.id) {
      const payment = await createPayment(contract.id, 5000, 'card');
    }

    // 5. Export data
    console.log('\n5. Exporting data...');
    const exportedData = await exportData('json', 'contracts');

    // 6. Create API token for future use
    console.log('\n6. Creating API token...');
    const token = await createApiToken('My App', ['read', 'write', 'payments'], '90d');

    console.log('\n=== Workflow Complete ===\n');
  } catch (error) {
    console.error('Workflow error:', error);
  }
}

/**
 * Error Handling Example
 */
async function handleErrors() {
  try {
    // Try to get non-existent contract
    await client.contracts.getContract({ contractId: 99999 });
  } catch (error: any) {
    if (error.response?.status === 404) {
      console.log('Contract not found');
    } else if (error.response?.status === 401) {
      console.log('Unauthorized - token may be expired');
    } else if (error.response?.status === 403) {
      console.log('Forbidden - insufficient permissions');
    } else {
      console.error('Unexpected error:', error.message);
    }
  }
}

/**
 * Retry Logic Example
 */
async function withRetry<T>(
  fn: () => Promise<T>,
  maxRetries: number = 3
): Promise<T> {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error: any) {
      if (attempt === maxRetries) {
        throw error;
      }
      // Exponential backoff
      const delay = Math.pow(2, attempt - 1) * 1000;
      console.log(`Attempt ${attempt} failed, retrying in ${delay}ms...`);
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }
  throw new Error('Max retries exceeded');
}

/**
 * Batch Operations Example
 */
async function batchCreateContracts(count: number) {
  console.log(`Creating ${count} contracts...`);
  const promises = Array.from({ length: count }, (_, i) =>
    createContract(`Contract ${i + 1}`, 1000 * (i + 1))
  );
  const results = await Promise.all(promises);
  console.log(`Created ${results.filter((r: any) => r).length} contracts`);
  return results;
}

// Export examples for use in other modules
export {
  getCurrentUser,
  loginUser,
  registerUser,
  listContracts,
  createContract,
  getContract,
  updateContract,
  deleteContract,
  createPayment,
  listPayments,
  exportData,
  createApiToken,
  listApiTokens,
  getTokenAuditLog,
  revokeApiToken,
  healthCheck,
  fullWorkflow,
  handleErrors,
  withRetry,
  batchCreateContracts
};

// Run example if executed directly
if (require.main === module) {
  (async () => {
    await getCurrentUser();
  })().catch(console.error);
}
